title: Purple Monkey Game Jam
description: > # The Purple Monkey Game Jam is a theme-based, non-competitive game jam spanning a full weekend where game makers can come together to practice their craft and learn from each other. A surprise theme will be announced at the beginning of the event and participants can then find a team or work alone to build a game based on the theme by the end of the weekend.
date: March 26th - 27th 2016
register_url: https://generalassemb.ly/education/purple-monkey-game-jam-vii/boston/21959
location: 51 Melcher Street, Boston, MA 02210
location_url: https://www.google.com/maps/place/51+Melcher+St,+Boston,+MA+02210/

markdown: kramdown
