title: Purple Monkey Game Jam X
description: > # The Purple Monkey Game Jam is a theme-based, non-competitive, two-day event where developers, artists, music composers, writers, and anyone who has an interest in building games get together to build something awesome. The theme of each event is picked at random from community sourced themes and announced the day of the event. Participants can join teams or work alone.
date: May 18th - 19th 2019
register_url: https://www.meetup.com/purplemonkeygamejam/events/260116208/
location: 320 Congress St, First Floor, Boston, MA
location_url: https://www.google.com/maps/place/100+Summer+St,+Boston,+MA+02110/@42.3538143,-71.0595797,17z/

markdown: kramdown
