title: Purple Monkey Game Jam
description: > # The Purple Monkey Game Jam is a theme-based, non-competitive, two-day event where developers, artists, music composers, writers, and anyone who has an interest in building games get together to build something awesome. The theme of each event is picked at random from community sourced themes and announced the day of the event. Participants can join teams or work alone.
date: April 22nd - 23rd 2017
register_url: https://www.meetup.com/purplemonkeygamejam/events/237966197/
location: 320 Congress St, First Floor, Boston, MA
location_url: https://www.google.com/maps/search/320+Congress+St,+First+Floor,+Boston,+MA/@42.3513204,-71.0516749,17z/data=!3m1!4b1

markdown: kramdown
permalink: blog/:title
